export const size: string;
export const sizeMessageItemAvatar: string;
export const avatar: string;
export const name: string;
export const messageLeft: string;
export const messageRight: string;
export const timeLeft: string;
export const timeRight: string;
export const clear: string;
