export const colors: string;
export const colorPrimary: string;
export const colorDark: string;
export const root: string;
export const bottom: string;
export const top: string;
export const imageMenuRoot: string;
export const on: string;
export const off: string;
